ALTER TABLE public.users 
ADD COLUMN password VARCHAR(255),
ADD COLUMN google_id VARCHAR(255) UNIQUE,
ADD COLUMN refresh_token TEXT,
ADD COLUMN password_reset_token VARCHAR(255),
ADD COLUMN password_reset_expires TIMESTAMP WITH TIME ZONE,
ADD COLUMN last_login TIMESTAMP WITH TIME ZONE,
ADD COLUMN last_active TIMESTAMP WITH TIME ZONE,
ADD COLUMN volunteer_id VARCHAR(50) UNIQUE;
